// Generated by https://quicktype.io

class CreditModel {
  String? profile_path;
  String? known_for_department;
  String? character;
  String? name;

  CreditModel({
    this.profile_path,
    this.known_for_department,
    this.character,
    this.name,
  });

  factory CreditModel.fromMap(Map<String, dynamic> map) {
    return CreditModel(
        profile_path: map['profile_path'] ?? '',
        //cualense ??, si es nulo lo de la izquierda
        //asigna lo de la derecha
        known_for_department: map['known_for_department'],
        character: map['character'],
        name: map['name']);
  }
}
