// Generated by https://quicktype.io

class Favorite_model {
  int? IdFav;
  String? Id_movie;

  Favorite_model({
    this.IdFav,
    this.Id_movie,
  });

  factory Favorite_model.fromMap(Map<String, dynamic> map) {
    return Favorite_model(
      IdFav: map['IdFav'] ?? '',
      //cualense ??, si es nulo lo de la izquierda
      //asigna lo de la derecha
      Id_movie: map['Id_movie'],
    );
  }
}
