// Generated by https://quicktype.io

class VideoModel {
  String? key;
  String? type;
  String? site;

  VideoModel({
    this.key,
    this.type,
    this.site,
  });

  factory VideoModel.fromMap(Map<String, dynamic> map) {
    return VideoModel(
      key: map['key'] ?? '',
      //cualense ??, si es nulo lo de la izquierda
      //asigna lo de la derecha
      type: map['type'],
      site: map['site'],
    );
  }
}
